# Generated by Django 5.1.2 on 2024-10-19 23:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'article")),
                ('text', models.CharField(blank=True, max_length=250, verbose_name='Paragraphe')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image')),
                ('image_description', models.CharField(blank=True, max_length=100, verbose_name="Description de l'image")),
                ('image_credit', models.CharField(blank=True, max_length=100, verbose_name='Crédit')),
            ],
            options={
                'verbose_name': 'À propos des JO',
                'verbose_name_plural': 'À propos des JO',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom de la version')),
                ('editor_name', models.CharField(blank=True, default='Webnoa', max_length=255, verbose_name="Nom de l'éditeur")),
                ('editor_website', models.URLField(blank=True, default='www.webnoa.fr', verbose_name="Site web de l'éditeur")),
                ('utilisation', models.CharField(blank=True, default='Utilisation par le Temple Saint-Etienne', max_length=255, verbose_name='Utilisation')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mentions légales',
                'verbose_name_plural': 'Mentions légales',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'offre")),
                ('max_adult', models.IntegerField(default=0, verbose_name="Nombre max de tickets adulte auquel l'offre ouvre droit")),
                ('min_adult', models.IntegerField(default=0, verbose_name="Nombre min de tickets adulte pour disposer de l'offre")),
                ('discount_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise sur le ticket adulte (%)')),
                ('with_child', models.BooleanField(default=False, verbose_name='Cette offre propose des tickets enfants')),
                ('max_child', models.IntegerField(default=0, verbose_name="Nombre max de tickets enfant auquel l'offre ouvre droit")),
                ('min_child', models.IntegerField(default=0, verbose_name="Nombre min de tickets enfant pour disposer de l'offre")),
                ('discount_child', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise sur le ticket enfant (%)')),
            ],
            options={
                'verbose_name': 'Offre',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'épreuve")),
                ('genre', models.CharField(choices=[('a', ''), ('b', 'féminin'), ('c', 'masculin')], default='a', max_length=10, verbose_name='Genre')),
                ('complete_name', models.CharField(blank=True, max_length=200, verbose_name='Épreuve')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et horaire de début')),
                ('standard_price', models.PositiveIntegerField(default=15, verbose_name='prix standard en €')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Épreuve',
            },
        ),
    ]
