# Generated by Django 5.1.2 on 2024-10-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='aboutjo',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Paragraphe'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='editor_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'éditeur"),
        ),
        migrations.AlterField(
            model_name='legal',
            name='editor_website',
            field=models.URLField(blank=True, default='', verbose_name="Site web de l'éditeur"),
        ),
        migrations.AlterField(
            model_name='legal',
            name='utilisation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Utilisation'),
        ),
    ]
