# Generated by Django 5.1.2 on 2024-10-20 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutjo',
            name='image_credit',
            field=models.CharField(blank=True, default="Image générée par l'IA", max_length=100, verbose_name='Crédit'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_child',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise sur le ticket enfant (%)'),
        ),
    ]
