# Generated by Django 5.1.2 on 2024-10-24 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_adult',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_child',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_adult',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_child',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_adult',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_child',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='with_child',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise sur le ticket (%)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='ticket_nb',
            field=models.IntegerField(default=0, verbose_name="Nombre de tickets auquel l'offre ouvre droit"),
        ),
    ]
