# Generated by Django 5.1.2 on 2024-10-24 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_offer_discount_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise sur le billet unitaire (%)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ticket_nb',
            field=models.IntegerField(default=0, verbose_name="Nombre de billets auquel l'offre ouvre droit"),
        ),
    ]
