# Generated by Django 5.1.2 on 2024-10-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_offer_discount_alter_offer_ticket_nb'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='host_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Adresse de l'hébergeur"),
        ),
        migrations.AddField(
            model_name='legal',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'hébergeur"),
        ),
        migrations.AddField(
            model_name='legal',
            name='host_website',
            field=models.URLField(blank=True, verbose_name='Site hébergeur'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Propriété intellectuelle'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Données personnelles'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Loi applicable'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_text_4',
            field=models.TextField(blank=True, null=True, verbose_name='Modification des mentions légales'),
        ),
        migrations.AlterField(
            model_name='aboutjo',
            name='text',
            field=models.TextField(blank=True, max_length=200, verbose_name='Paragraphe'),
        ),
    ]
