# Generated by Django 5.1.2 on 2024-10-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Vente'},
        ),
        migrations.AlterField(
            model_name='order',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
