# Generated by Django 5.1.2 on 2024-10-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_options_alter_order_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='order',
            name='children',
        ),
    ]
