# Generated by Django 5.1.2 on 2024-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_order_adults_remove_order_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_nb',
            field=models.IntegerField(default=0, verbose_name='Nombre de billets'),
        ),
    ]
